version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    depends_on:
      - db
    image: watzek/omeka:latest
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      OMEKA_DB_HOST: db:3306
      OMEKA_DB_USER: omeka
      OMEKA_DB_PASSWORD: omeka
      OMEKA_DB_NAME: omeka
      OMEKA_DB_PREFIX: _omeka
      OMEKA_DB_CHARSET: utf8
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
      APPLICATION_ENV: development
